# Generated by Django 5.0.1 on 2024-02-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.IntegerField(choices=[(0, 'Cliente'), (1, 'Médico'), (2, 'Nutricionista'), (3, 'Preparador físico'), (4, 'Administrador')])),
                ('horario', models.DateTimeField()),
                ('duracao_em_minutos', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Agendada'), (1, 'Cancelada'), (2, 'Realizada'), (3, 'Vencida')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancariosRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.IntegerField(choices=[(0, 'Cliente'), (1, 'Médico'), (2, 'Nutricionista'), (3, 'Preparador físico'), (4, 'Administrador')])),
                ('agencia', models.CharField(max_length=4)),
                ('conta', models.CharField(max_length=9)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_curta', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('duracao_em_dias', models.IntegerField(blank=True, null=True)),
                ('calorias', models.IntegerField(verbose_name=models.CharField(blank=True, null=True))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('ocupacao', models.IntegerField(choices=[(0, 'Cliente'), (1, 'Médico'), (2, 'Nutricionista'), (3, 'Preparador físico'), (4, 'Administrador')])),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_de_nascimento', models.DateField()),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('nivel_de_acucar_no_sangue', models.FloatField(blank=True, null=True)),
                ('gordura_no_figado', models.IntegerField(blank=True, null=True)),
                ('hemoglobina_glicada', models.FloatField(blank=True, null=True)),
                ('producao_de_insulina', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioNutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes_adicionais', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioPreparadorFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('nivel_de_atividade_fisica', models.IntegerField(blank=True, choices=[(0, 'Muito Ativo'), (1, 'Ativo'), (2, 'Insuficientemente Ativo A'), (3, 'Insuficientemente Ativo B'), (4, 'Sedentário')], null=True)),
                ('gasto_calorico', models.IntegerField(blank=True, null=True)),
                ('metabolismo_basal', models.IntegerField(blank=True, null=True)),
                ('porcentagem_de_gordura', models.FloatField(blank=True, null=True)),
                ('porcentage_de_musculo', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consulta')),
                ('treino_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.treinofisico')),
            ],
        ),
        migrations.CreateModel(
            name='PreparadorFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=13)),
                ('especialidade', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_cartao', models.CharField(max_length=16)),
                ('validade', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
