# Generated by Django 5.0.1 on 2024-03-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosta', models.CharField(blank=True, max_length=300, null=True)),
                ('desgosta', models.CharField(blank=True, max_length=300, null=True)),
                ('alergias', models.CharField(blank=True, max_length=300, null=True)),
                ('doencas', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('relatorio_nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.relatorionutricionista')),
            ],
        ),
    ]
