# Generated by Django 5.0.1 on 2024-03-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_consulta_paciente_alter_consulta_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='calorias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
