# Generated by Django 5.0.1 on 2024-03-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_consulta_paciente_alter_consulta_profissional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.CharField(max_length=200)),
                ('tipo_diabetes', models.IntegerField(choices=[(0, 'Não possui'), (1, 'Tipo 1'), (2, 'Tipo 2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='DadosBancarios',
        ),
    ]
