# Generated by Django 5.0.1 on 2024-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(choices=[(0, 'Feminino'), (1, 'Masculino'), (2, 'Não binário'), (3, 'Prefiro não informar'), (4, 'Outro')], default=3),
            preserve_default=False,
        ),
    ]
