# Generated by Django 5.0.1 on 2024-03-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dieta_calorias'),
        ('api', '0006_alter_usuario_genero'),
    ]

    operations = [
    ]
