# Generated by Django 5.0.1 on 2024-03-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20240313_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinofisico',
            name='profissional',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AddField(
            model_name='treinofisico',
            name='titulo',
            field=models.CharField(default='Treino Genérico', max_length=50),
        ),
        migrations.AlterField(
            model_name='treinofisico',
            name='treino',
            field=models.CharField(max_length=2000),
        ),
    ]
