# Generated by Django 5.0.1 on 2024-03-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20240313_1617'),
        ('api', '0007_merge_20240320_1414'),
    ]

    operations = [
    ]
