# Generated by Django 5.0.1 on 2024-03-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pedidoexamemedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoexamemedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_medico', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='pedidoexamemedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_paciente', to='api.usuario'),
        ),
    ]
