# Generated by Django 5.0.1 on 2024-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pedidoexamemedico_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoexamemedico',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Finalizada')], default=1),
            preserve_default=False,
        ),
    ]
