# Generated by Django 5.0.1 on 2024-03-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pedidoexamenutricionista_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorionutricionista',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dieta'),
        ),
    ]
