# Generated by Django 5.0.1 on 2024-03-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_treinofisico_profissional_treinofisico_titulo_and_more'),
        ('api', '0009_pedidoexamenutricionista_status'),
        ('api', '0010_pedidoexamemedico_status'),
    ]

    operations = [
    ]
