# Generated by Django 5.0.1 on 2024-03-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20240320_1458'),
        ('api', '0011_merge_20240325_1903'),
    ]

    operations = [
    ]
