# Generated by Django 5.0.1 on 2024-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_relatorionutricionista_dieta'),
        ('api', '0012_merge_20240329_1610'),
    ]

    operations = [
    ]
