# Generated by Django 5.0.1 on 2024-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_consulta_tarifa_consulta_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
