# Generated by Django 5.0.1 on 2024-04-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20240329_1610'),
        ('api', '0013_alter_paciente_alergias'),
    ]

    operations = [
    ]
