# Generated by Django 5.0.1 on 2024-04-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_extusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
