# Generated by Django 5.0.1 on 2024-04-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_usuario_email_remove_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancariosrecebimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_conta', to='api.usuario'),
        ),
    ]
