# Generated by Django 5.0.1 on 2024-04-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20240409_1128'),
        ('api', '0017_alter_dadosbancariosrecebimento_profissional'),
    ]

    operations = [
    ]
