# Generated by Django 5.0.1 on 2024-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20240410_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='extusuario',
            name='ocupacao',
            field=models.IntegerField(choices=[(0, 'Paciente'), (1, 'Médico'), (2, 'Nutricionista'), (3, 'Preparador físico'), (4, 'Administrador')], default=0),
            preserve_default=False,
        ),
    ]
