# Generated by Django 5.0.1 on 2024-04-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_extusuario_ocupacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriopreparadorfisico',
            name='treino_fisico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.treinofisico'),
        ),
    ]
