name: Deploy hosting portion of website

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
      
    - name: Build website with env variables
      working-directory: ./front
      run: |
        touch .env
        echo REACT_APP_PROTOCOL_HOSTNAME_PORT=${{ secrets.API_PROTOCOL_HOSTNAME_PORT }} >> .env
        npm install
        npm run build
      env:
        CI: ""
        
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
      with:
        source-path: front/build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
