name: Deploy API

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - api/**
      - plataforma_digital/**
      - Dockerfile

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: rafnak1
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (app1)
        id: metadata
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: rafnak1/labengsoft:api

      - name: Build and push Docker image api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rafnak1/labengsoft:api
          labels: ${{ steps.metadata.outputs.labels }}
          secrets: |
            "DB_PASSWORD=${{ secrets.SQL_PASSWORD }}"
            "TARIFA_URL_CODE=${{ secrets.TARIFA_URL_CODE }}"
            "PAGAMENTO_URL_CODE=${{ secrets.PAGAMENTO_URL_CODE }}"

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
    
      - name: copy docker-compose.yml via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOSTNAME }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          source: "docker-compose.yml"
          target: $HOME/deploy
          
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOSTNAME }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            cd $HOME/deploy
            docker login -u rafnak1 -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull rafnak1/labengsoft:api
            docker compose down api
            docker compose up -d api
            
