name: Deploy hosting portion of website

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
      
    - name: Build website with env variables
      working-directory: ./front
      env:
        CI: ""
        API_PROTOCOL_HOSTNAME_PORT: ${{ secrets.API_PROTOCOL_HOSTNAME_PORT }}
        TOKEN_URL: ${{ secrets.TOKEN_URL }}
        PACIENTE_LOGIN_URL: ${{ secrets.PACIENTE_LOGIN_URL }}
        PACIENTE_AUTH_SECRET: ${{ secrets.PACIENTE_AUTH_SECRET }}
        MEDICO_LOGIN_URL: ${{ secrets.MEDICO_LOGIN_URL }}
        MEDICO_AUTH_SECRET: ${{ secrets.MEDICO_AUTH_SECRET }}
        NUTRICIONISTA_LOGIN_URL: ${{ secrets.NUTRICIONISTA_LOGIN_URL }}
        NUTRICIONISTA_AUTH_SECRET: ${{ secrets.NUTRICIONISTA_AUTH_SECRET }}
      run: |
        touch .env
        echo REACT_APP_ENVIRONMENT=prod >> .env
        echo REACT_APP_PROTOCOL_HOSTNAME_PORT="$API_PROTOCOL_HOSTNAME_PORT" >> .env
        echo REACT_APP_TOKEN_URL="$TOKEN_URL" >> .env
        echo REACT_APP_PACIENTE_LOGIN_URL="$PACIENTE_LOGIN_URL" >> .env
        echo REACT_APP_PACIENTE_AUTH_SECRET="$PACIENTE_AUTH_SECRET" >> .env
        echo REACT_APP_MEDICO_LOGIN_URL="$MEDICO_LOGIN_URL" >> .env
        echo REACT_APP_MEDICO_AUTH_SECRET="$MEDICO_AUTH_SECRET" >> .env
        echo REACT_APP_NUTRICIONISTA_LOGIN_URL="$NUTRICIONISTA_LOGIN_URL" >> .env
        echo REACT_APP_NUTRICIONISTA_AUTH_SECRET="$NUTRICIONISTA_AUTH_SECRET" >> .env
        npm install
        npm run build
        
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
      with:
        source-path: front/build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
